fixed uui issue and npm audit
microsoft/semanticworkbench pull request #6
Opened 2024-07-30 22:57 UTC by kdcllc

there were issues running sample locally with uuid in service

2024-07-31 20:16 UTC, dluc commented on semantic-workbench/v1/app/package-lock.json
do we need the changes in this file? unless there are changes also in `package.json` I think we can keep the original file

2024-07-31 22:56 UTC, kdcllc commented on semantic-workbench/v1/app/package-lock.json
@dluc I had to run `npm audit fix` to fix critical issues with packages

2024-08-01 17:56 UTC, dluc commented on examples/dotnet-example02/appsettings.json
> +    "ApiKey": "616c3edc5550418f801a27c90d6c01de"
please undo these changes -- the key will remain in the repo history even after updating the PR, so I recommend invalidating it ASAP

2024-08-01 17:58 UTC, dluc requested changes
- undo changes to package-lock.json
- undo changes to appsettings.json
- invalidate personal API key

2024-08-02 17:59 UTC, closed without merging